version: "2"
checks:
  method-lines:
    config:
      threshold: 30
exclude_patterns:
  - ".github/"
  - "config/"
  - "dist/"
  - "docs/"
  - "test/"
  - "tools/"
  - "**/node_modules/"
  - "**/*.d.ts"
  - "src/**/*parser.js"
  - "src/render/**/*.template.cjs"
